name:                typed-assembly
version:             0.1.0.0
github:              "elpinal/typed-assembly/haskell"
license:             MIT
author:              "El Pin Al"
maintainer:          ""
copyright:           "2018 El Pin Al"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/elpinal/typed-assembly#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.10.2

library:
  source-dirs: src

executables:
  typed-assembly-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typed-assembly

tests:
  typed-assembly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typed-assembly
    - hspec
